import type { Metadata } from "next"
import { Work_Sans } from "next/font/google"
import "./globals.css"

const font = Work_Sans({ subsets: ["latin"], weight: ["400", "600", "700"] })

export const metadata: Metadata = {
  title: "Frontend Mentor | FAQ Accordian",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} relative flex flex-col items-center min-h-screen pt-[155px] bg-light-pink px-6`}
      >
        <div className="absolute top-0 left-0 w-screen -z-10 bg-mobile mobile:bg-desktop h-[320px]" />
        {children}
      </body>
    </html>
  )
}
