import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

import "./globals.css";
import Banner from "@/components/ui/Banner";
import Footer from "@/components/ui/Footer";

const font = Work_Sans({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata: Metadata = {
	title: "Frontend Mentor | FAQ Accordian",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${font.className} relative flex min-h-screen flex-col items-center gap-6 bg-light-pink px-6 pb-6 pt-[160px]`}
			>
				<Banner />
				{children}
				<Footer />
			</body>
		</html>
	);
}
